import { PetSpecies } from '@/types/pet/pet-enums';
import type {
    Activity,
    Allergy,
    Grooming,
    KidLevel,
    SpaceScore,
    Vibe,
} from '../types/questionnaire';

export interface BreedProfile {
  name: string;
  species: PetSpecies;
  fitScore: number;
  why: string;
  tags: string[];
  preferences: {
    kidLevel: KidLevel[];
    spaceScore: SpaceScore[];
    allergy: Allergy[];
    vibe: Vibe[];
    grooming: Grooming[];
    activity: Activity[];
  };
  weights: {
    kidLevel: number;
    spaceScore: number;
    allergy: number;
    vibe: number;
    grooming: number;
    activity: number;
  };
}

export const breedProfiles: Record<string, BreedProfile> = {
  // CAT BREEDS
  ragdoll: {
    name: 'Ragdoll',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Flops into fun without fight; indoor zen master—top 2025 kid pick.',
    tags: ['lap-legend', 'gentle-guardian'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'none'],
      spaceScore: [1, 2, 3],
      allergy: ['high', 'none'],
      vibe: ['cuddly', 'playful'],
      grooming: ['high', 'medium'],
      activity: ['low', 'medium'],
    },
    weights: {
      kidLevel: 3,
      spaceScore: 2,
      allergy: 2,
      vibe: 3,
      grooming: 2,
      activity: 2,
    },
  },
  birman: {
    name: 'Birman',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Shadow-stalker playmate; allergy-armored, yard? What yard?',
    tags: ['hypo', 'playful-pal'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [1, 2, 3, 4],
      allergy: ['high', 'none'],
      vibe: ['cuddly', 'playful'],
      grooming: ['high', 'medium'],
      activity: ['medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 3,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  britishShorthair: {
    name: 'British Shorthair',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Calm, sturdy companion perfect for families and seniors; low-maintenance and adaptable.',
    tags: ['calm-companion', 'family-friendly'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [2, 3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['independent', 'cuddly'],
      grooming: ['low', 'medium'],
      activity: ['low', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 1,
      vibe: 2,
      grooming: 3,
      activity: 2,
    },
  },
  persian: {
    name: 'Persian',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Gentle, quiet lap cat ideal for calm homes and seniors; requires regular grooming.',
    tags: ['gentle-soul', 'low-energy'],
    preferences: {
      kidLevel: ['teens', 'none'],
      spaceScore: [2, 3, 4],
      allergy: ['none'],
      vibe: ['cuddly', 'independent'],
      grooming: ['high'],
      activity: ['low'],
    },
    weights: {
      kidLevel: 3,
      spaceScore: 2,
      allergy: 2,
      vibe: 3,
      grooming: 3,
      activity: 3,
    },
  },
  maineCoon: {
    name: 'Maine Coon',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Gentle giant with dog-like personality; great with kids and other pets.',
    tags: ['gentle-giant', 'family-friendly'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'cuddly'],
      grooming: ['high', 'medium'],
      activity: ['medium', 'high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 1,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  siamese: {
    name: 'Siamese',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Vocal, social, and playful; thrives in active households with attention.',
    tags: ['social-butterfly', 'vocal'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [2, 3, 4],
      allergy: ['none'],
      vibe: ['playful', 'cuddly'],
      grooming: ['low'],
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 2,
      vibe: 3,
      grooming: 3,
      activity: 3,
    },
  },
  scottishFold: {
    name: 'Scottish Fold',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Sweet, adaptable companion; perfect for apartments, quiet families, and seniors.',
    tags: ['sweet-tempered', 'adaptable'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [1, 2, 3],
      allergy: ['none', 'otherPets'],
      vibe: ['cuddly', 'independent'],
      grooming: ['medium', 'low'],
      activity: ['low', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 1,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  sphynx: {
    name: 'Sphynx',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Hairless wonder seeking warmth and attention; perfect for allergy sufferers.',
    tags: ['hypo', 'attention-seeker'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [2, 3, 4],
      allergy: ['high'],
      vibe: ['cuddly', 'playful'],
      grooming: ['high', 'medium'], // Needs bathing
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 1,
      spaceScore: 1,
      allergy: 4,
      vibe: 3,
      grooming: 1,
      activity: 2,
    },
  },
  russianBlue: {
    name: 'Russian Blue',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Hypoallergenic beauty with gentle demeanor; perfect for allergy-prone families and seniors.',
    tags: ['hypo', 'gentle'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [1, 2, 3, 4],
      allergy: ['high', 'none'],
      vibe: ['independent', 'cuddly'],
      grooming: ['low'],
      activity: ['medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 3,
      vibe: 2,
      grooming: 3,
      activity: 2,
    },
  },
  abyssinian: {
    name: 'Abyssinian',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Energetic explorer loves active play; ideal for families with older kids.',
    tags: ['active', 'playful'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none'],
      vibe: ['playful', 'independent'],
      grooming: ['low'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 2,
      vibe: 3,
      grooming: 3,
      activity: 3,
    },
  },
  bengal: {
    name: 'Bengal',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Wild-looking but friendly; needs space and stimulation for active families.',
    tags: ['active', 'unique'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'independent'],
      grooming: ['low'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 1,
      vibe: 3,
      grooming: 3,
      activity: 3,
    },
  },
  norwegianForest: {
    name: 'Norwegian Forest Cat',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Friendly giant adapts well to families; loves climbing and exploring.',
    tags: ['family-friendly', 'active'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'cuddly'],
      grooming: ['high', 'medium'],
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 1,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  devonRex: {
    name: 'Devon Rex',
    species: PetSpecies.CAT,
    fitScore: 0,
    why: 'Curly-coated clown loves attention; hypoallergenic and apartment-friendly.',
    tags: ['hypo', 'playful'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [1, 2, 3],
      allergy: ['high', 'none'],
      vibe: ['playful', 'cuddly'],
      grooming: ['low'],
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 3,
      vibe: 3,
      grooming: 3,
      activity: 2,
    },
  },
  // DOG BREEDS
  goldenRetriever: {
    name: 'Golden Retriever',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Ultimate family dog; patient, friendly, and great with kids of all ages.',
    tags: ['family-friendly', 'gentle'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'cuddly'],
      grooming: ['high', 'medium'],
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 3,
      spaceScore: 3,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 3,
    },
  },
  labrador: {
    name: 'Labrador Retriever',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Energetic and loving; perfect active companion for families with space.',
    tags: ['active', 'family-friendly'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'cuddly'],
      grooming: ['medium', 'low'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 3,
      spaceScore: 3,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 3,
    },
  },
  beagle: {
    name: 'Beagle',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Friendly and curious; great with kids but needs regular exercise.',
    tags: ['family-friendly', 'active'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [2, 3, 4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'independent'],
      grooming: ['low'],
      activity: ['high', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 1,
      vibe: 2,
      grooming: 3,
      activity: 3,
    },
  },
  poodle: {
    name: 'Poodle',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Hypoallergenic and intelligent; comes in sizes for any space.',
    tags: ['hypo', 'smart'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [1, 2, 3, 4, 5],
      allergy: ['high', 'none'],
      vibe: ['playful', 'cuddly'],
      grooming: ['high'],
      activity: ['medium', 'high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 1,
      allergy: 4,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  frenchBulldog: {
    name: 'French Bulldog',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Low-energy apartment dweller; gentle and great for small spaces and seniors.',
    tags: ['apartment-friendly', 'gentle'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [1, 2, 3],
      allergy: ['none'],
      vibe: ['cuddly', 'independent'],
      grooming: ['low'],
      activity: ['low'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 2,
      vibe: 2,
      grooming: 3,
      activity: 3,
    },
  },
  cavalierKingCharles: {
    name: 'Cavalier King Charles Spaniel',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Gentle lap dog perfect for families and seniors; adaptable to any living situation.',
    tags: ['gentle', 'adaptable'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [1, 2, 3, 4],
      allergy: ['none', 'otherPets'],
      vibe: ['cuddly', 'playful'],
      grooming: ['medium', 'high'],
      activity: ['low', 'medium'],
    },
    weights: {
      kidLevel: 3,
      spaceScore: 2,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 2,
    },
  },
  borderCollie: {
    name: 'Border Collie',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Highly intelligent and energetic; needs active families with space.',
    tags: ['smart', 'active'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'independent'],
      grooming: ['medium'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 4,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 3,
    },
  },
  shihTzu: {
    name: 'Shih Tzu',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Small, affectionate companion; perfect for apartments, gentle families, and seniors.',
    tags: ['apartment-friendly', 'gentle'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [1, 2, 3],
      allergy: ['none'],
      vibe: ['cuddly', 'independent'],
      grooming: ['high'],
      activity: ['low', 'medium'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 3,
      allergy: 2,
      vibe: 2,
      grooming: 2,
      activity: 2,
    },
  },
  australianShepherd: {
    name: 'Australian Shepherd',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Energetic herder loves active families; needs space and mental stimulation.',
    tags: ['active', 'smart'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'independent'],
      grooming: ['medium'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 4,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 3,
    },
  },
  corgi: {
    name: 'Corgi',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Big personality in small package; friendly and great with families.',
    tags: ['family-friendly', 'playful'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [2, 3, 4],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'cuddly'],
      grooming: ['medium'],
      activity: ['medium', 'high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 2,
    },
  },
  husky: {
    name: 'Siberian Husky',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Energetic and friendly; needs active families with plenty of space.',
    tags: ['active', 'friendly'],
    preferences: {
      kidLevel: ['school', 'teens', 'none'],
      spaceScore: [4, 5],
      allergy: ['none', 'otherPets'],
      vibe: ['playful', 'independent'],
      grooming: ['medium', 'high'],
      activity: ['high'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 4,
      allergy: 1,
      vibe: 3,
      grooming: 2,
      activity: 3,
    },
  },
  bulldog: {
    name: 'Bulldog',
    species: PetSpecies.DOG,
    fitScore: 0,
    why: 'Calm and gentle; perfect for families and seniors seeking a low-energy companion.',
    tags: ['calm', 'gentle'],
    preferences: {
      kidLevel: ['toddlers', 'school', 'teens', 'none'],
      spaceScore: [2, 3, 4],
      allergy: ['none'],
      vibe: ['cuddly', 'independent'],
      grooming: ['low'],
      activity: ['low'],
    },
    weights: {
      kidLevel: 2,
      spaceScore: 2,
      allergy: 2,
      vibe: 2,
      grooming: 3,
      activity: 3,
    },
  },
};
