import { PetSpecies } from '@/types/pet/pet-enums';

export const DOG_BREEDS = [
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'French Bulldog',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'German Shorthaired Pointer',
  'Yorkshire Terrier',
  'Siberian Husky',
  'Dachshund',
  'Boxer',
  'Great Dane',
  'Chihuahua',
  'Shih Tzu',
  'Boston Terrier',
  'Border Collie',
  'Australian Shepherd',
  'Cocker Spaniel',
  'Maltese',
  'Jack Russell Terrier',
  'Pomeranian',
  'Doberman Pinscher',
  'Mastiff',
  'Basset Hound',
  'Weimaraner',
  'Dalmatian',
  'Saint Bernard',
  'Brittany',
  'Mixed Breed',
  'Other',
];

export const CAT_BREEDS = [
  'Persian',
  'Maine Coon',
  'British Shorthair',
  'Ragdoll',
  'Sphynx',
  'Scottish Fold',
  'American Shorthair',
  'Abyssinian',
  'Siamese',
  'Russian Blue',
  'Norwegian Forest Cat',
  'Bengal',
  'Devon Rex',
  'Cornish Rex',
  'Oriental Shorthair',
  'Himalayan',
  'Exotic Shorthair',
  'Burmese',
  'Siberian',
  'Tonkinese',
  'Bombay',
  'Manx',
  'Munchkin',
  'Savannah',
  'Egyptian Mau',
  'Turkish Angora',
  'Somali',
  'Chartreux',
  'Havana Brown',
  'American Curl',
  'Mixed Breed',
  'Other',
];

export const BIRD_BREEDS = [
  'Budgerigar (Budgie)',
  'Cockatiel',
  'Canary',
  'Lovebird',
  'Cockatoo',
  'African Grey Parrot',
  'Amazon Parrot',
  'Conure',
  'Finch',
  'Zebra Finch',
  'Society Finch',
  'Gouldian Finch',
  'Cockatiel',
  'Sun Conure',
  'Green Cheek Conure',
  'Quaker Parrot',
  'Indian Ringneck',
  'Eclectus',
  'Macaw',
  'Cockatoo',
  'Parakeet',
  'Other',
];

export const RABBIT_BREEDS = [
  'Holland Lop',
  'Netherland Dwarf',
  'Mini Rex',
  'Lionhead',
  'Flemish Giant',
  'English Lop',
  'French Lop',
  'American Fuzzy Lop',
  'Mini Lop',
  'Himalayan',
  'Dutch',
  'Polish',
  'Rex',
  'Satin',
  'Californian',
  'New Zealand',
  'Havana',
  "Champagne D'Argent",
  'American',
  'Belgian Hare',
  'Other',
];

export const HAMSTER_BREEDS = [
  'Syrian Hamster',
  'Dwarf Campbell Russian',
  'Dwarf Winter White Russian',
  'Dwarf Roborovski',
  'Chinese Hamster',
  'European Hamster',
  'Other',
];

export const GUINEA_PIG_BREEDS = [
  'American',
  'Abyssinian',
  'Peruvian',
  'Silkie',
  'Teddy',
  'Texel',
  'Coronet',
  'Lunkarya',
  'Merino',
  'Alpaca',
  'Other',
];

export const FISH_BREEDS = [
  'Goldfish',
  'Betta',
  'Guppy',
  'Tetra',
  'Angelfish',
  'Cichlid',
  'Molly',
  'Platy',
  'Swordtail',
  'Danio',
  'Barbs',
  'Discus',
  'Oscar',
  'Koi',
  'Neon Tetra',
  'Cardinal Tetra',
  'Cherry Barb',
  'Zebra Danio',
  'Pearl Gourami',
  'Dwarf Gourami',
  'Other',
];

export const REPTILE_BREEDS = [
  'Ball Python',
  'Corn Snake',
  'Bearded Dragon',
  'Leopard Gecko',
  'Crested Gecko',
  'Blue Tongue Skink',
  'Iguana',
  'Chameleon',
  'Tortoise',
  'Turtle',
  'Boa Constrictor',
  'King Snake',
  'Milk Snake',
  'Garter Snake',
  'Anole',
  'Other',
];

export const HORSE_BREEDS = [
  'Thoroughbred',
  'Quarter Horse',
  'Arabian',
  'Paint Horse',
  'Appaloosa',
  'Mustang',
  'Friesian',
  'Clydesdale',
  'Percheron',
  'Tennessee Walking Horse',
  'Morgan',
  'Standardbred',
  'Warmblood',
  'Pony',
  'Other',
];

export const OTHER_BREEDS = [
  'Ferret',
  'Chinchilla',
  'Hedgehog',
  'Sugar Glider',
  'Rat',
  'Mouse',
  'Gerbil',
  'Degus',
  'Other',
];

export const POPULAR_BREEDS: Record<string, string[]> = {
  [PetSpecies.DOG]: DOG_BREEDS,
  [PetSpecies.CAT]: CAT_BREEDS,
  [PetSpecies.BIRD]: BIRD_BREEDS,
  [PetSpecies.RABBIT]: RABBIT_BREEDS,
  [PetSpecies.HAMSTER]: HAMSTER_BREEDS,
  [PetSpecies.FISH]: FISH_BREEDS,
  [PetSpecies.REPTILE]: REPTILE_BREEDS,
  [PetSpecies.HORSE]: HORSE_BREEDS,
  [PetSpecies.OTHER]: OTHER_BREEDS,
};

export const getBreedsForSpecies = (species: PetSpecies): string[] => {
  return POPULAR_BREEDS[species] || OTHER_BREEDS;
};
